// Curated list of well-known cities for the Novario Newsroom.
// Population is kept in the type for future use but never shown in the UI.
export type City = { city: string; country: string; pop?: number };

export const INDIA_CITIES: City[] = [
  { city: "Delhi", country: "India" },
  { city: "Mumbai", country: "India" },
  { city: "Kolkata", country: "India" },
  { city: "Bangalore", country: "India" },
  { city: "Chennai", country: "India" },
  { city: "Hyderabad", country: "India" },
  { city: "Pune", country: "India" },
  { city: "Ahmedabad", country: "India" },
  { city: "Surat", country: "India" },
  { city: "Prayagraj", country: "India" },
  { city: "Lucknow", country: "India" },
  { city: "Jaipur", country: "India" },
  { city: "Nagpur", country: "India" },
  { city: "Ghaziabad", country: "India" },
  { city: "Vadodara", country: "India" },
  { city: "Rajkot", country: "India" },
  { city: "Visakhapatnam", country: "India" },
  { city: "Indore", country: "India" },
  { city: "Thane", country: "India" },
  { city: "Bhopal", country: "India" },
  { city: "Agra", country: "India" },
  { city: "Pimpri-Chinchwad", country: "India" },
  { city: "Patna", country: "India" },
  { city: "Ludhiana", country: "India" },
  { city: "Madurai", country: "India" },
  { city: "Jamshedpur", country: "India" },
  { city: "Nashik", country: "India" },
  { city: "Vijayawada", country: "India" },
  { city: "Faridabad", country: "India" },
  { city: "Meerut", country: "India" },
  { city: "Jabalpur", country: "India" },
  { city: "Varanasi", country: "India" },
  { city: "Srinagar", country: "India" },
  { city: "Aurangabad", country: "India" },
  { city: "Amritsar", country: "India" },
  { city: "Guwahati", country: "India" },
  { city: "Ranchi", country: "India" },
  { city: "Gwalior", country: "India" },
  { city: "Chandigarh", country: "India" },
  { city: "Jodhpur", country: "India" },
  { city: "Raipur", country: "India" },
  { city: "Kochi", country: "India" },
  { city: "Coimbatore", country: "India" },
  { city: "Mysuru", country: "India" },
  { city: "Dehradun", country: "India" },
  { city: "Bhubaneswar", country: "India" },
  { city: "Goa", country: "India" },
  { city: "Shimla", country: "India" },
];

export const WORLD_CITIES: City[] = [
  { city: "New York", country: "United States" },
  { city: "London", country: "United Kingdom" },
  { city: "Tokyo", country: "Japan" },
  { city: "Paris", country: "France" },
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Singapore", country: "Singapore" },
  { city: "Hong Kong", country: "Hong Kong" },
  { city: "Sydney", country: "Australia" },
  { city: "Toronto", country: "Canada" },
  { city: "Berlin", country: "Germany" },
  { city: "Moscow", country: "Russia" },
  { city: "Beijing", country: "China" },
  { city: "Shanghai", country: "China" },
  { city: "Seoul", country: "South Korea" },
  { city: "Bangkok", country: "Thailand" },
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "Jakarta", country: "Indonesia" },
  { city: "Manila", country: "Philippines" },
  { city: "Karachi", country: "Pakistan" },
  { city: "Dhaka", country: "Bangladesh" },
  { city: "Istanbul", country: "Turkey" },
  { city: "Tehran", country: "Iran" },
  { city: "Riyadh", country: "Saudi Arabia" },
  { city: "Cairo", country: "Egypt" },
  { city: "Johannesburg", country: "South Africa" },
  { city: "Lagos", country: "Nigeria" },
  { city: "Nairobi", country: "Kenya" },
  { city: "Mexico City", country: "Mexico" },
  { city: "São Paulo", country: "Brazil" },
  { city: "Rio de Janeiro", country: "Brazil" },
  { city: "Buenos Aires", country: "Argentina" },
  { city: "Lima", country: "Peru" },
  { city: "Bogota", country: "Colombia" },
  { city: "Los Angeles", country: "United States" },
  { city: "Chicago", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Washington", country: "United States" },
  { city: "Miami", country: "United States" },
  { city: "Vancouver", country: "Canada" },
  { city: "Madrid", country: "Spain" },
  { city: "Barcelona", country: "Spain" },
  { city: "Rome", country: "Italy" },
  { city: "Milan", country: "Italy" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Brussels", country: "Belgium" },
  { city: "Vienna", country: "Austria" },
  { city: "Zurich", country: "Switzerland" },
  { city: "Stockholm", country: "Sweden" },
  { city: "Oslo", country: "Norway" },
  { city: "Copenhagen", country: "Denmark" },
  { city: "Dublin", country: "Ireland" },
  { city: "Lisbon", country: "Portugal" },
  { city: "Athens", country: "Greece" },
  { city: "Warsaw", country: "Poland" },
  { city: "Prague", country: "Czechia" },
  { city: "Tel Aviv", country: "Israel" },
  { city: "Doha", country: "Qatar" },
  { city: "Auckland", country: "New Zealand" },
];
