export type Language = {
  code: string;
  native: string;
  english: string;
  region: string;
};

// 70+ language-region combinations + the special "Zulad" entry
export const LANGUAGES: Language[] = [
  { code: "en-IN", native: "English", english: "English", region: "India" },
  { code: "en-US", native: "English", english: "English", region: "United States" },
  { code: "en-GB", native: "English", english: "English", region: "United Kingdom" },
  { code: "en-AU", native: "English", english: "English", region: "Australia" },
  { code: "en-CA", native: "English", english: "English", region: "Canada" },
  { code: "en-NZ", native: "English", english: "English", region: "New Zealand" },
  { code: "en-IE", native: "English", english: "English", region: "Ireland" },
  { code: "en-ZA", native: "English", english: "English", region: "South Africa" },
  { code: "hi-IN", native: "हिन्दी", english: "Hindi", region: "India" },
  { code: "bn-IN", native: "বাংলা", english: "Bengali", region: "India" },
  { code: "bn-BD", native: "বাংলা", english: "Bengali", region: "Bangladesh" },
  { code: "ta-IN", native: "தமிழ்", english: "Tamil", region: "India" },
  { code: "te-IN", native: "తెలుగు", english: "Telugu", region: "India" },
  { code: "mr-IN", native: "मराठी", english: "Marathi", region: "India" },
  { code: "gu-IN", native: "ગુજરાતી", english: "Gujarati", region: "India" },
  { code: "kn-IN", native: "ಕನ್ನಡ", english: "Kannada", region: "India" },
  { code: "ml-IN", native: "മലയാളം", english: "Malayalam", region: "India" },
  { code: "pa-IN", native: "ਪੰਜਾਬੀ", english: "Punjabi", region: "India" },
  { code: "or-IN", native: "ଓଡ଼ିଆ", english: "Odia", region: "India" },
  { code: "as-IN", native: "অসমীয়া", english: "Assamese", region: "India" },
  { code: "ur-IN", native: "اردو", english: "Urdu", region: "India" },
  { code: "ur-PK", native: "اردو", english: "Urdu", region: "Pakistan" },
  { code: "ne-NP", native: "नेपाली", english: "Nepali", region: "Nepal" },
  { code: "si-LK", native: "සිංහල", english: "Sinhala", region: "Sri Lanka" },
  { code: "es-ES", native: "Español", english: "Spanish", region: "Spain" },
  { code: "es-MX", native: "Español", english: "Spanish", region: "Mexico" },
  { code: "es-AR", native: "Español", english: "Spanish", region: "Argentina" },
  { code: "es-CO", native: "Español", english: "Spanish", region: "Colombia" },
  { code: "es-CL", native: "Español", english: "Spanish", region: "Chile" },
  { code: "es-US", native: "Español", english: "Spanish", region: "United States" },
  { code: "pt-BR", native: "Português", english: "Portuguese", region: "Brazil" },
  { code: "pt-PT", native: "Português", english: "Portuguese", region: "Portugal" },
  { code: "fr-FR", native: "Français", english: "French", region: "France" },
  { code: "fr-CA", native: "Français", english: "French", region: "Canada" },
  { code: "fr-BE", native: "Français", english: "French", region: "Belgium" },
  { code: "fr-CH", native: "Français", english: "French", region: "Switzerland" },
  { code: "de-DE", native: "Deutsch", english: "German", region: "Germany" },
  { code: "de-AT", native: "Deutsch", english: "German", region: "Austria" },
  { code: "de-CH", native: "Deutsch", english: "German", region: "Switzerland" },
  { code: "it-IT", native: "Italiano", english: "Italian", region: "Italy" },
  { code: "nl-NL", native: "Nederlands", english: "Dutch", region: "Netherlands" },
  { code: "nl-BE", native: "Nederlands", english: "Dutch", region: "Belgium" },
  { code: "sv-SE", native: "Svenska", english: "Swedish", region: "Sweden" },
  { code: "no-NO", native: "Norsk", english: "Norwegian", region: "Norway" },
  { code: "da-DK", native: "Dansk", english: "Danish", region: "Denmark" },
  { code: "fi-FI", native: "Suomi", english: "Finnish", region: "Finland" },
  { code: "is-IS", native: "Íslenska", english: "Icelandic", region: "Iceland" },
  { code: "pl-PL", native: "Polski", english: "Polish", region: "Poland" },
  { code: "cs-CZ", native: "Čeština", english: "Czech", region: "Czechia" },
  { code: "sk-SK", native: "Slovenčina", english: "Slovak", region: "Slovakia" },
  { code: "hu-HU", native: "Magyar", english: "Hungarian", region: "Hungary" },
  { code: "ro-RO", native: "Română", english: "Romanian", region: "Romania" },
  { code: "bg-BG", native: "Български", english: "Bulgarian", region: "Bulgaria" },
  { code: "el-GR", native: "Ελληνικά", english: "Greek", region: "Greece" },
  { code: "tr-TR", native: "Türkçe", english: "Turkish", region: "Türkiye" },
  { code: "ru-RU", native: "Русский", english: "Russian", region: "Russia" },
  { code: "uk-UA", native: "Українська", english: "Ukrainian", region: "Ukraine" },
  { code: "ar-SA", native: "العربية", english: "Arabic", region: "Saudi Arabia" },
  { code: "ar-AE", native: "العربية", english: "Arabic", region: "UAE" },
  { code: "ar-EG", native: "العربية", english: "Arabic", region: "Egypt" },
  { code: "ar-MA", native: "العربية", english: "Arabic", region: "Morocco" },
  { code: "he-IL", native: "עברית", english: "Hebrew", region: "Israel" },
  { code: "fa-IR", native: "فارسی", english: "Persian", region: "Iran" },
  { code: "zh-CN", native: "中文", english: "Chinese (Simplified)", region: "China" },
  { code: "zh-TW", native: "中文", english: "Chinese (Traditional)", region: "Taiwan" },
  { code: "zh-HK", native: "中文", english: "Chinese (Cantonese)", region: "Hong Kong" },
  { code: "ja-JP", native: "日本語", english: "Japanese", region: "Japan" },
  { code: "ko-KR", native: "한국어", english: "Korean", region: "South Korea" },
  { code: "th-TH", native: "ไทย", english: "Thai", region: "Thailand" },
  { code: "vi-VN", native: "Tiếng Việt", english: "Vietnamese", region: "Vietnam" },
  { code: "id-ID", native: "Bahasa Indonesia", english: "Indonesian", region: "Indonesia" },
  { code: "ms-MY", native: "Bahasa Melayu", english: "Malay", region: "Malaysia" },
  { code: "fil-PH", native: "Filipino", english: "Filipino", region: "Philippines" },
  { code: "km-KH", native: "ខ្មែរ", english: "Khmer", region: "Cambodia" },
  { code: "my-MM", native: "မြန်မာ", english: "Burmese", region: "Myanmar" },
  { code: "sw-KE", native: "Kiswahili", english: "Swahili", region: "Kenya" },
  { code: "am-ET", native: "አማርኛ", english: "Amharic", region: "Ethiopia" },
  { code: "yo-NG", native: "Yorùbá", english: "Yoruba", region: "Nigeria" },
  { code: "zu-ZA", native: "isiZulu", english: "Zulu", region: "South Africa" },
  // Hidden door — placed naturally in the alphabetical tail, not highlighted
  { code: "zulad", native: "Zulad", english: "Zulad", region: "" },
];
