/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OviiRouteImport } from './routes/ovii'
import { Route as NewsRouteImport } from './routes/news'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const OviiRoute = OviiRouteImport.update({
  id: '/ovii',
  path: '/ovii',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/ovii': typeof OviiRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/ovii': typeof OviiRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/ovii': typeof OviiRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news' | '/ovii' | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/ovii' | '/news/$slug'
  id: '__root__' | '/' | '/news' | '/ovii' | '/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRouteWithChildren
  OviiRoute: typeof OviiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ovii': {
      id: '/ovii'
      path: '/ovii'
      fullPath: '/ovii'
      preLoaderRoute: typeof OviiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRouteWithChildren,
  OviiRoute: OviiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
